/*
 * Copyright (c) 2018 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
 */

#ifndef BT_LBS_H_
#define BT_LBS_H_

/**@file
 * @defgroup bt_lbs LED Button Service API
 * @{
 * @brief API for the LED Button Service (LBS).
 */

#ifdef __cplusplus
extern "C"
{
#endif

#include <zephyr/types.h>

/** @brief App configuration Service UUID. */
#define BT_UUID_APP_CONFIG_VAL \
    BT_UUID_128_ENCODE(0x00001523, 0x1212, 0xefde, 0x1523, 0x785feabcd123)

/** @brief App runtime Service UUID. */
#define BT_UUID_APP_RUNTIME_VAL \
    BT_UUID_128_ENCODE(0x00001524, 0x1212, 0xefde, 0x1523, 0x785feabcd123)


#define BT_UUID_UNIX_TIME_VAL \
    BT_UUID_128_ENCODE(0xc0dec0fe, 0xcafe, 0xa1ca, 0x992f, 0x1b1b1b1b1b1b)
#define BT_UUID_BATTERY_LEVEL_VAL \
    BT_UUID_128_ENCODE(0xc0dec0fe, 0x0bad, 0x41c7, 0x992f, 0xa5d063dbfeee)
#define BT_UUID_TRANSMIT_POWER_VAL \
    BT_UUID_128_ENCODE(0xb1eec10a, 0x0007, 0x4d3c, 0xa1ca, 0xae3e7e098a2b)
#define BT_UUID_DEVICE_NAME_VAL \
    BT_UUID_128_ENCODE(0x00002a00, 0x0000, 0x1000, 0x8000, 0x00805f9b34fb)
#define BT_UUID_FIRMWARE_REVISION_STRING_VAL \
    BT_UUID_128_ENCODE(0xcabacafe, 0xf00d, 0x4b1b, 0x9b1b, 0x1b1b1b1b1b1b)
#define BT_UUID_DEVICE_LOG_VAL \
    BT_UUID_128_ENCODE(0xbeefc0de, 0xf00d, 0x4d3c, 0xa1ca, 0xae3e7e098a2b)
    #define BT_UUID_DEVICE_LOG_LENGTH_VAL \
    BT_UUID_128_ENCODE(0xbeefd1fa, 0xf00d, 0x4d3c, 0xa1ca, 0xae3e7e098a2b)
#define BT_UUID_MEMORY_ALLOCATED_PERCENTAGE_VAL \
    BT_UUID_128_ENCODE(0xdeadc0de, 0xbeef, 0x4b1b, 0x9b1b, 0x1b1b1b1b1b1b)
#define BT_UUID_SENSOR_DATA_LENGTH_VAL \
    BT_UUID_128_ENCODE(0x0badf00d, 0xcafe, 0x4b1b, 0x9b1b, 0x2c931b1b1b1b)
#define BT_UUID_RESPONSE_TIMEOUT_VAL \
    BT_UUID_128_ENCODE(0xf007face, 0xbabe, 0x47f5, 0xb542, 0xbbfd9b436872)
#define BT_UUID_SENSOR_DATA_VAL \
    BT_UUID_128_ENCODE(0xc0debabe, 0xface, 0x4f89, 0xb07d, 0xf9d9b20a76c8)
#define BT_UUID_CLEAR_FLASH_DATA_DISCONNECT_BIT_VAL \
    BT_UUID_128_ENCODE(0xcabba6ee, 0xc0de, 0x4414, 0xa6f6, 0x46a397e18422)
#define BT_UUID_ADVERTISING_INTERVAL_GLOBAL_VAL \
    BT_UUID_128_ENCODE(0xeeafbeef, 0xcafe, 0x4d3c, 0xa1ca, 0xae3e7e098a2b)
#define BT_UUID_ADVERTISING_DURATION_VAL \
    BT_UUID_128_ENCODE(0xbabebeef, 0xcafe, 0x4d3c, 0xa1ca, 0xae3e7e098a2b)
#define BT_UUID_ADVERTISING_INTERVAL_LOCAL_VAL \
    BT_UUID_128_ENCODE(0xc0ffee00, 0xbabe, 0x4d3c, 0xa1ca, 0xae3e7e098a2b)

#define BT_UUID_APP_RUNTIME BT_UUID_DECLARE_128(BT_UUID_APP_RUNTIME_VAL)
#define BT_UUID_APP_CONFIG BT_UUID_DECLARE_128(BT_UUID_APP_CONFIG_VAL)

#define BT_UUID_UNIX_TIME BT_UUID_DECLARE_128(BT_UUID_UNIX_TIME_VAL)
#define BT_UUID_BATTERY_LEVEL BT_UUID_DECLARE_128(BT_UUID_BATTERY_LEVEL_VAL)
#define BT_UUID_TRANSMIT_POWER BT_UUID_DECLARE_128(BT_UUID_TRANSMIT_POWER_VAL)
#define BT_UUID_DEVICE_NAME BT_UUID_DECLARE_128(BT_UUID_DEVICE_NAME_VAL)
#define BT_UUID_FIRMWARE_REVISION_STRING BT_UUID_DECLARE_128(BT_UUID_FIRMWARE_REVISION_STRING_VAL)
#define BT_UUID_DEVICE_LOG BT_UUID_DECLARE_128(BT_UUID_DEVICE_LOG_VAL)
#define BT_UUID_DEVICE_LOG_LENGTH BT_UUID_DECLARE_128(BT_UUID_DEVICE_LOG_LENGTH_VAL)
#define BT_UUID_MEMORY_ALLOCATED_PERCENTAGE BT_UUID_DECLARE_128(BT_UUID_MEMORY_ALLOCATED_PERCENTAGE_VAL)
#define BT_UUID_SENSOR_DATA_LENGTH BT_UUID_DECLARE_128(BT_UUID_SENSOR_DATA_LENGTH_VAL)
#define BT_UUID_RESPONSE_TIMEOUT BT_UUID_DECLARE_128(BT_UUID_RESPONSE_TIMEOUT_VAL)
#define BT_UUID_SENSOR_DATA BT_UUID_DECLARE_128(BT_UUID_SENSOR_DATA_VAL)
#define BT_UUID_CLEAR_FLASH_DATA_DISCONNECT_BIT BT_UUID_DECLARE_128(BT_UUID_CLEAR_FLASH_DATA_DISCONNECT_BIT_VAL)
#define BT_UUID_ADVERTISING_INTERVAL_GLOBAL BT_UUID_DECLARE_128(BT_UUID_ADVERTISING_INTERVAL_GLOBAL_VAL)
#define BT_UUID_ADVERTISING_DURATION BT_UUID_DECLARE_128(BT_UUID_ADVERTISING_DURATION_VAL)
#define BT_UUID_ADVERTISING_INTERVAL_LOCAL BT_UUID_DECLARE_128(BT_UUID_ADVERTISING_INTERVAL_LOCAL_VAL)

#define FILE_BT_CHAR_DEVICE_LOG FILE_CHAR_LOCATION "/dev_log"
#define FILE_BT_CHAR_DEVICE_LOG_LENGTH FILE_CHAR_LOCATION "/dev_log_len"

#define FILE_BT_CHAR_TRANSMIT_POWER FILE_CHAR_LOCATION "/t_power"
#define FILE_BT_CHAR_RESPONSE_TIMEOUT FILE_CHAR_LOCATION "/resp_timeout"
#define FILE_BT_CHAR_ADVERTISING_INTERVAL_GLOBAL FILE_CHAR_LOCATION "/adv_int_g"
#define FILE_BT_CHAR_ADVERTISING_DURATION FILE_CHAR_LOCATION "/adv_dur"
#define FILE_BT_CHAR_ADVERTISING_INTERVAL_LOCAL FILE_CHAR_LOCATION "/adv_int_l"

int restore_char_values(void);

uint64_t get_sync_unix_time_ms(void);
uint16_t get_sensor_odr_hz(void);
uint64_t get_uptime_at_sync_ms(void);
void set_sensor_data_length(uint32_t length);
uint32_t get_sensor_data_length(void);
bool get_sensor_data_read_in_progress(void);
void set_sensor_data_read_in_progress(bool state);
uint16_t get_adv_dur_ms(void);
uint16_t get_adv_int_g_ms(void);

#ifdef __cplusplus
}
#endif

/**
 * @}
 */

#endif /* BT_LBS_H_ */